### ISSUE TITLE
Displaying settings values near the keys

### ISSUE THREAD

**Issue by opk12** [stride-tasks/stride#14]
Stealing a pattern seen in other Android apps: in the Settings page, for the entries URL - e-mail - author - branch, what about displaying the value near the key? Maybe in brackets, or greyed out, to make it clear that it is the value.

    Branch [main]

    Branch
    [main]

**Comment by HalidOdat** [comment]
I initially had it like this, but when the value is to long it looks wraps which doesn't look that nice. One way would be to maybe truncate it with `valu...`.

**Comment by opk12** [comment]
Yes, the e-mail and author can probably be guessed just from seeing the first part.
